#! /usr/local/bin/bash

source `dirname ${0}`/Krnl.include

((cd ${VELPATHTOKRNSRCS} && make -j${VELNUMCPUS} KERNFAST= buildworld ) \
     > ${BLDERROUT} 2>&1 || (less '+/error: ' ${BLDERROUT} 2>&1; \
         exit 1) && tail -n 20 $BLDERROUT )

