#! /usr/local/bin/bash

source `dirname ${0}`/Krnl.include

( (cd ${VELPATHTOKRNSRCS} && make -j${VELNUMCPUS} KERNFAST= buildkernel ) \
     > ${BLDERROUT} 2>&1 || (less '+/error: ' ${BLDERROUT} 2>&1; \
         exit 1) && tail -n 20 $BLDERROUT )

echo ${MODS_FIND_LOCATION}
