#! /bin/sh

VELPATHTOKRNSRCS=$(cd `dirname ${0}`/../FBSD12-20181207/./; echo $PWD)
export KERNBUILDDIR=$(cd ${VELPATHTOKRNSRCS}/../../obj/./; echo $PWD)
export MAKEOBJDIRPREFIX=${KERNBUILDDIR}

export BLDNSTLERROUT="$TEMP/buildinstall.errout"
export KERNCONF=VEL01-DEBUG
export MODULES_OVERRIDE="rdma ibcore linuxkpi mlx5 mlx5ib mlx5en nvd dtrace opensolaris"

( (cd ${VELPATHTOKRNSRCS} && make -j36 buildkernel && make -j36 installkernel) \
     > ${BLDNSTLERROUT} 2>&1 || (less '+error: ' ${BLDNSTLERROUT} 2>&1; \
         exit 1) && tail -n 20 $BLDNSTLERROUT )

