#! /usr/local/bin/bash

source `dirname ${0}`/Krnl.include

( (cd ${VELPATHTOKRNSRCS} && make -j36 installkernel) \
     > ${NSTLERROUT} 2>&1 || (less '+error: ' ${NSTLERROUT} 2>&1; \
         exit 1) && tail -n 20 $NSTLERROUT )

