#! /usr/local/bin/bash

source `dirname ${0}`/Krnl.include

export TMPDIR=/tmp/${LOGNAME}; export TEMP=${TMPDIR}
( (cd ${VELPATHTOKRNSRCS} && make -j36 installworld) \
     > ${NSTLERROUT} 2>&1 || (less '+error: ' ${NSTLERROUT} 2>&1; \
         exit 1) && tail -n 20 $NSTLERROUT )

